[phases.setup]
nixPkgs = ["go"]

[phases.install]
cmd = "go mod download"

[phases.build]
cmd = "GOOS=linux GOARCH=amd64 go build -ldflags='-s' -o=./bin/linux_amd64/api ./cmd/api"

[start]
cmd = "./bin/linux_amd64/api"

